### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by hadynz** [dalekjs/skaro#1]
What's the chance that I am able to help to contribute to the `skaro` phase of the project?

Keen to pick something from the backlog and submitting it as a pull request but wasn't sure on the backlog order and priority.

I've been using Dalek on many projects and would love to help out in making it more awesome!

**Comment by hadynz** [comment]
Thanks for your responses guys. I will have a squiz through the new API's as suggested and drop any feedback accordingly. If you are getting more responses like mine, it might indeed pay off to invest some proj management to get other people contributing.

No fuss.

PS: Apologies for the lateness in reply. I was expecting to get an email notification from GitHub when you have replied to my thread and just occurred to me today that there might be a response that I didn't notice.

**Comment by elliotboney** [comment]
I am also interested in helping if you could put together a quick "How To Help" guide or even outline of where to begin.

**Comment by rodneyrehm** [comment]
We (Sebastian, me, anyone who wants to join) are going on the third Dalekathon™ in April. We should have a working prototype of the new system after that. We'll focus on adressing all the [open topics](https://github.com/dalekjs/skaro#open-topics) required to actually get things running, as well as figure out how to *approach* the other API issues. If others join the Dalekathon™ we might even get to tackle some of the documentation concerns.

But the ultimate goal is to get something like version 0.0.1 ready by end of April. Something that "mostly works". Something that provides the structure for others to join the effort of fleshing out.

A specific date has not yet been set for the Dalekathon, nor have we settled on a city yet. It's likely going to be 3-5 days, mid/end of April, somewhere in Germany.

We're sorry things are moving this slowly. I can throw a bunch of excuses at you - but you already know how easily life derails any plans you might've had…

**Comment by SuneRadich** [comment]
This all sound very promising. But as someone who only recently discovered DalekJS, and someone who is about to start using some sort of automated browser testing - I am confused.

As I understand it, Skaro is a playground for how/where DalekJS is is moving along. Does that mean that DalekJS in its current version will be deprecated? Can I a start using DalekJS in its current version?

**Comment by rodneyrehm** [comment]
> As I understand it, Skaro is a playground for how/where DalekJS is is moving along. 

yes. Since we decided to start from scratch it made sense to do that in a different respository that we could throw away if we didn't like what we did. (which is not the case. We like where we're headed)

> Does that mean that DalekJS in its current version will be deprecated?

Eventually, yes. Skaro will become the next version of Dalek. But this is not going to happen any time soon.

> Can I a start using DalekJS in its current version?

The current version of DalekJS is what dalekjs.com is offering. This version can be used. Skaro, however, is not remotely ready to be used for actual testing. Once we have Skaro on satisfactory level, we will investigate what we need to provide a backward-compatibility-API so you can still run your "old-Dalek" tests in Skaro (which will become "Dalek" at some point, of course).

**Comment by rodneyrehm** [comment]
The third Dalekathon is done. In an attempt to keep development as open and transparent as possible, we wrote up a [report on what was achieved and decided](https://github.com/dalekjs/skaro/wiki/3rd-Dalekathon---Report).

The next (fourth) Dalekathon™ is planned for June 4th - 7th. It is going to take place in Cologne (Germany) or remote (virtual office via Google Hangouts).

**Comment by Timopheym** [comment]
Hey @rodneyrehm, what about fourth Dalekathon™? I need a test engine for my product, and Dalek looks very promising.

**Comment by rodneyrehm** [comment]
Hey @Timopheym, we've had to bail on the Dalekathon planned for last week. We're currently figure out what we can do in June to compensate. And another one in July is planned as well.

Are you interested in contributing to the development of Dalek, or do you simply want to use the final thing?

**Comment by Timopheym** [comment]
@rodneyrehm We need a test engine with drivers to phantomjs, headless IE, gecko and selenium that can navigate between pages, upload files and run scripts in page context, if new Dalek will support it i will contribute it with pleasure (But for now i get the error running scaro.. )
```
Timopheys-MacBook-Pro:skaro timopheym$ bin/dalek.cli.js run --config=example/browser-config.json --browser chrome
Warning: Ignoring »/private/var/www/testingengine/skaro/example/plugins/example-plugin.js« because the function does not expect exactly 1 parameter


behavior is not defined
 at  (/private/var/www/testingengine/skaro/node_modules/dalek-driver-chrome/index.js:45)
Timopheys-MacBook-Pro:skaro timopheym$ bin/dalek.cli.js run --config=example/browser-config.json --browser gustav
Warning: Ignoring »/private/var/www/testingengine/skaro/example/plugins/example-plugin.js« because the function does not expect exactly 1 parameter
module.js:338
    throw err;
          ^
Error: Cannot find module 'underscore.string'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/var/www/testingengine/skaro/node_modules/wd/lib/lodash.js:2:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
Timopheys-MacBook-Pro:skaro timopheym$ bin/dalek.cli.js run --config=example/browser-config.json
Warning: Ignoring »/private/var/www/testingengine/skaro/example/plugins/example-plugin.js« because the function does not expect exactly 1 parameter
module.js:338
    throw err;
          ^
Error: Cannot find module 'underscore.string'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/var/www/testingengine/skaro/node_modules/wd/lib/lodash.js:2:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by rodneyrehm** [comment]
> We need a test engine with drivers to phantomjs, headless IE, gecko and selenium that can navigate between pages, upload files and run scripts in page context, if new Dalek will support it i will contribute it with pleasure

Eventually all these things should be possible (except maybe headless IE, not sure if that's a thing). At the moment we're still getting version 0.1.0 ready, which will be the foundation for contributions, *not* a version suitable for production.

> (But for now i get the error running scaro.. )

looks like we hit a typo. I fixed it in master.
